version: '1.0'

services:
  # Django 后端服务
  backend:
    image: 
    container_name: django-backend
    restart: always
    environment:
      - AUTOBAHN_USE_UVLOOP=0
      - TWISTED_REACTOR=asyncio
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  # Vue 前端服务
  frontend:
    image: 
    container_name: vben-admin-frontend
    ports:
      - "8012:80"
    depends_on:
      - backend
    restart: always